export type ChatType = "private" | "group";

export type MessageStatus = "sent" | "delivered" | "seen";

export type ContactRequestStatus =
  | "pending"
  | "accepted"
  | "rejected"
  | "cancelled";

export interface Profile {
  id: string;
  username: string | null;
  full_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  created_at: string;
  last_seen: string | null;
  is_online: boolean;
}

export interface Chat {
  id: string;
  type: ChatType;
  name: string | null;
  avatar_url: string | null;
  created_at: string;
  is_group: boolean;
}

export type ChatMemberRole = "owner" | "admin" | "member";

export interface ChatMember {
  id: string;
  chat_id: string;
  user_id: string;
  role: ChatMemberRole;
}

export interface Message {
  id: string;
  chat_id: string;
  sender_id: string;
  content: string | null;
  media_url: string | null;
  created_at: string;
  status: MessageStatus;
  parent_id?: string | null;
  reactions?: Record<string, string[]>; // emoji -> [userIds]
}

export interface AiMessage {
  id: string;
  user_id: string;
  content: string;
  response: string;
  created_at: string;
}

export interface MessageReaction {
  id: string;
  message_id: string;
  user_id: string;
  emoji: string;
  created_at: string;
}

export interface ContactRequest {
  id: string;
  requester_id: string;
  target_id: string;
  status: ContactRequestStatus;
  created_at: string;
  updated_at: string;
}

// Minimal Database type for supabase-js generic typing.
// You can replace this with types generated by Supabase CLI if desired.
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: Partial<
          Omit<Profile, "created_at" | "is_online" | "last_seen">
        >;
        Update: Partial<Omit<Profile, "id" | "created_at">>;
      };
      chats: {
        Row: Chat;
        Insert: Partial<Omit<Chat, "id" | "created_at">>;
        Update: Partial<Omit<Chat, "id">>;
      };
      chat_members: {
        Row: ChatMember;
        Insert: Partial<Omit<ChatMember, "id">>;
        Update: Partial<Omit<ChatMember, "id">>;
      };
      messages: {
        Row: Message;
        Insert: Partial<Omit<Message, "id" | "created_at" | "status">>;
        Update: Partial<Omit<Message, "id" | "chat_id" | "sender_id">>;
      };
      ai_messages: {
        Row: AiMessage;
        Insert: {
          user_id: string;
          content: string;
          response: string;
          created_at?: string;
        };
        Update: Partial<Omit<AiMessage, "id" | "user_id">>;
      };
      message_reactions: {
        Row: MessageReaction;
        Insert: {
          message_id: string;
          user_id: string;
          emoji: string;
          created_at?: string;
        };
        Update: Partial<Omit<MessageReaction, "id" | "message_id" | "user_id">>;
      };
      contact_requests: {
        Row: ContactRequest;
        Insert: {
          requester_id: string;
          target_id: string;
          status?: ContactRequestStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<ContactRequest, "id" | "requester_id" | "target_id" | "created_at">>;
      };
    };
    Functions: {
      get_messages_per_day: {
        Args: { days_limit: number };
        Returns: { day: string; count: number }[];
      };
      get_signups_per_day: {
        Args: { days_limit: number };
        Returns: { day: string; count: number }[];
      };
      get_active_by_hour: {
        Args: Record<string, never>;
        Returns: { hour: number; count: number }[];
      };
      get_avg_response_time: {
        Args: Record<string, never>;
        Returns: number;
      };
      get_read_ratio_over_time: {
        Args: { days_limit: number };
        Returns: { day: string; read_count: number; unread_count: number }[];
      };
    };
    Views: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

